-- Discovery mode of the desktop app: a private library per user plus reading
-- data (see "Enhancement of the desktop app v2.0.md", Phase 3, and
-- backend/src/library.js).
--
-- library_items      books a user imported (file kept privately on the server,
--                    never served to anyone but its owner) and Crowdly stories
--                    they read in Discovery.
-- reading_positions  one position per user and item: percent plus an exact,
--                    format-specific locator; narration (audio) kept apart so
--                    listening ahead never moves the place reached by eye.
-- reading_sessions   active reading time. The id is generated by the client,
--                    so a retried upload never counts twice.
-- reading_highlights versioned highlights; a deletion is a tombstone until
--                    every device acknowledged it (reading_sync_acks).

CREATE TABLE IF NOT EXISTS library_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES local_users(id) ON DELETE CASCADE,
  kind text NOT NULL,
  story_title_id uuid REFERENCES story_title(story_title_id) ON DELETE SET NULL,
  title text NOT NULL DEFAULT '',
  author text NOT NULL DEFAULT '',
  language text NOT NULL DEFAULT '',
  format text NOT NULL DEFAULT 'text',
  file_sha256 text,
  file_size bigint,
  storage_key text,
  rights_status text NOT NULL DEFAULT 'unknown',
  rights_declared_at timestamptz,
  visibility text NOT NULL DEFAULT 'private',
  converted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'library_items_kind_check') THEN
    ALTER TABLE library_items ADD CONSTRAINT library_items_kind_check
      CHECK (kind IN ('imported_book', 'crowdly_story'));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'library_items_format_check') THEN
    ALTER TABLE library_items ADD CONSTRAINT library_items_format_check
      CHECK (format IN ('epub', 'pdf', 'audio', 'text'));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'library_items_rights_check') THEN
    ALTER TABLE library_items ADD CONSTRAINT library_items_rights_check
      CHECK (rights_status IN ('unknown', 'personal_copy', 'own_work', 'public_domain', 'cc_licensed'));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'library_items_visibility_check') THEN
    ALTER TABLE library_items ADD CONSTRAINT library_items_visibility_check
      CHECK (visibility IN ('private', 'converted'));
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS library_items_user_idx ON library_items (user_id) WHERE deleted_at IS NULL;
-- One copy of a file per account (dedupe is per user, never across users).
CREATE UNIQUE INDEX IF NOT EXISTS library_items_user_sha_idx
  ON library_items (user_id, file_sha256)
  WHERE deleted_at IS NULL AND file_sha256 IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS library_items_user_story_idx
  ON library_items (user_id, story_title_id)
  WHERE deleted_at IS NULL AND kind = 'crowdly_story';

CREATE TABLE IF NOT EXISTS reading_positions (
  user_id uuid NOT NULL REFERENCES local_users(id) ON DELETE CASCADE,
  library_item_id uuid NOT NULL REFERENCES library_items(id) ON DELETE CASCADE,
  percent real NOT NULL DEFAULT 0,
  locator jsonb NOT NULL DEFAULT '{}'::jsonb,
  narration jsonb,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, library_item_id)
);

CREATE TABLE IF NOT EXISTS reading_sessions (
  id uuid PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES local_users(id) ON DELETE CASCADE,
  library_item_id uuid NOT NULL REFERENCES library_items(id) ON DELETE CASCADE,
  started_at timestamptz NOT NULL,
  ended_at timestamptz NOT NULL,
  seconds integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS reading_sessions_user_item_idx ON reading_sessions (user_id, library_item_id);
CREATE INDEX IF NOT EXISTS reading_sessions_user_started_idx ON reading_sessions (user_id, started_at);

CREATE SEQUENCE IF NOT EXISTS reading_highlights_version_seq;

CREATE TABLE IF NOT EXISTS reading_highlights (
  id uuid PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES local_users(id) ON DELETE CASCADE,
  library_item_id uuid NOT NULL REFERENCES library_items(id) ON DELETE CASCADE,
  color text NOT NULL DEFAULT 'yellow',
  note text NOT NULL DEFAULT '',
  quote text NOT NULL DEFAULT '',
  locator jsonb NOT NULL DEFAULT '{}'::jsonb,
  deleted boolean NOT NULL DEFAULT false,
  version bigint NOT NULL DEFAULT nextval('reading_highlights_version_seq'),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS reading_highlights_item_version_idx
  ON reading_highlights (user_id, library_item_id, version);

CREATE TABLE IF NOT EXISTS reading_sync_acks (
  user_id uuid NOT NULL REFERENCES local_users(id) ON DELETE CASCADE,
  device_id text NOT NULL,
  library_item_id uuid NOT NULL REFERENCES library_items(id) ON DELETE CASCADE,
  acked_version bigint NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, device_id, library_item_id)
);
